stages:
  - test
  - dockerize

test project:
  stage: test
  image: node:16
  script:
    - npm -v
    - npm install npm@8.5.0 -g
    - npm i
    - npm run test-component
    - npm run test-contract

dockerize project:
  stage: dockerize
  image: docker:20.10.8
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

