stages:
  - test
  - pact-publish
  - dockerize
  - deploy2test
  - deploy2production


# test project:
#   stage: test
#   image: node:16
#   script:
#     - npm -v
#     - npm install npm@8.5.0 -g
#     - npm i
#     - npm run test-component
#     - npm run test-contract

# dockerize project and push to heroku registryy
dockerize project:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker build --platform linux/amd64 -t registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web

# deploy to heroku test environment
deploy to test:
  stage: deploy2test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker pull registry.heroku.com/$HEROKU_APP_NAME/web
    - docker tag registry.heroku.com/$HEROKU_APP_NAME/web registry.heroku.com/$HEROKU_APP_NAME-test/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME-test/web
    - heroku container:release web -a $HEROKU_APP_NAME-test

# deploy to heroku production environment
deploy to production:
  stage: deploy2production
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker pull registry.heroku.com/$HEROKU_APP_NAME/web
    - docker tag registry.heroku.com/$HEROKU_APP_NAME/web registry.heroku.com/$HEROKU_APP_NAME-prod/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME-prod/web 
    - heroku container:release web -a $HEROKU_APP_NAME-prod