stages:
  # - test
  - pact-publish
  - dockerize
  - deploy2test
  - deploy2production

test project:
  stage: test
  image: node:16
  script:
    - npm -v
    - npm install npm@8.5.0 -g
    - npm i
    - npm run test-component
    - npm run test-contract

publish pact broker:
  stage: pact-publish
  image:
    name: pactfoundation/pact-cli:latest
    entrypoint: [""]
  variables:
    PACT_BROKER_CHECK_FOR_POTENTIAL_DUPLICATE_PACTICIPANT_NAMES : "false"
  script:
    - pact-broker create-or-update-pacticipant pact/pacts 
        --name "TodoFrontend"
        --consumer-app-version=$CI_COMMIT_SHORT_SHA 
        --tag=$CI_COMMIT_REF_NAME 
        --broker-base-url=$PACT_BROKER_BASE_URL 
        --broker-token=$PACT_BROKER_TOKEN

dockerize project:
  stage: dockerize
  image: docker:20.10.13
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy project to test:
  stage: deploy2test
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=modanisa-todo-app-test --api-key=$HEROKU_API_KEY


deploy project to production:
  stage: deploy2production
  image: docker:20.10.13
  services:
    - docker:dind
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=modanisa-todo-app-production --api-key=$HEROKU_API_KEY