stages:
  # - test
  # - pact-publish
  - dockerize
  - deploy2test
  - deploy2production

# test project:
#   stage: test
#   image: node:16
#   script:
#     - npm -v
#     - npm install npm@8.5.0 -g
#     - npm i
#     - npm run test-component
#     - npm run test-contract

# publish pact broker:
#   stage: pact-publish
#   image:
#     name: pactfoundation/pact-cli:latest
#     entrypoint: [""]
#   variables:
#     PACT_BROKER_CHECK_FOR_POTENTIAL_DUPLICATE_PACTICIPANT_NAMES : "false"
#   script:
#     - pact-broker create-or-update-pacticipant pact/pacts 
#         --name "TodoFrontend"
#         --consumer-app-version=$CI_COMMIT_SHORT_SHA 
#         --tag=$CI_COMMIT_REF_NAME 
#         --broker-base-url=$PACT_BROKER_BASE_URL 
#         --broker-token=$PACT_BROKER_TOKEN

# Dockerize the application and push the heroku container registry
dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web

# Deploy the dockerized application to heroku test envirounment
deploy2test:
  stage: deploy2test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull registry.heroku.com/$HEROKU_APP_NAME/web
    - docker tag registry.heroku.com/$HEROKU_APP_NAME/web registry.heroku.com/$HEROKU_APP_NAME-test/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME-test/web:latest
    - heroku container:release web --app $HEROKU_APP_NAME-test

# Deploy the dockerized application to heroku production envirounment
deploy2production:
  stage: deploy2production
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull registry.heroku.com/$HEROKU_APP_NAME/web
    - docker tag registry.heroku.com/$HEROKU_APP_NAME/web registry.heroku.com/$HEROKU_APP_NAME-production/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME-production/web
    - heroku container:release web --app $HEROKU_APP_NAME-production