stages:
  - test
  - dockerize
  - deploy2test

test project:
  stage: test
  image: node:16
  script:
    - npm -v
    - npm install npm@8.5.0 -g
    - npm i
    - npm run test-component
    - npm run test-contract

dockerize project:
  stage: dockerize
  image: docker:20.10.13
  services:
    - docker:dind
  script:
    - npm install npm@8.5.0 -g
    - npm i
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# deploy project to test:
#   stage: deploy2test
#   image: docker:20.10.13
#   services:
#     - docker:dind
#   script:
#     - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#     - gem install dpl
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY